### ISSUE TITLE
SIT-2708: Should curation result posts be saved in a site option?

### ISSUE THREAD

**Issue by barryceelen** [globeandmail/sophi-for-wordpress#153]
It seems the curation request result for each widget, which I suppose is the list of posts Sophi returns for a widget, is stored in an option:

https://github.com/globeandmail/sophi-for-wordpress/blob/develop/includes/classes/SiteAutomation/Request.php#L82

I'm wondering how big that response is, and if it should be stored in an option at all. I'm thinking it is generally not good form to use the options table for this type of data, which could also lead to issues with options caching. It might be better to store that data elsewhere, eg. in a custom post type.

**Comment by jeffpaul** [comment]
Flagging for @felipeelia to review / consider best approach if a change is needed.

**Comment by felipeelia** [comment]
I think @Rahmon will have a better opinion on this one but yeah, it seems that can result in a bunch of options being created ([our best practices guide mentions a total limit of 500](https://10up.github.io/Engineering-Best-Practices/php/#appropriate-data-storage).) Changing that can be a huge lift though. So, short term I'd change those options to not autoload (that should be done asap) and then migrate to a CPT.

**Comment by barryceelen** [comment]
Relatedly, It also looks like the plugin never purges the sophi_site_automation_data_... options. If you stop using a particular widget, there is no functionality that removes its related options.

**Comment by jeffpaul** [comment]
Relates to https://voltron.atlassian.net/servicedesk/customer/portal/41/SIT-2708
