### ISSUE TITLE
SIT-2935: get_the_terms() can return an array, false or WP_Error

### ISSUE THREAD

**Issue by barryceelen** [globeandmail/sophi-for-wordpress#190]
get_post_breadcrumb() [uses count() on the result of get_the_terms()](https://github.com/globeandmail/sophi-for-wordpress/blob/develop/includes/functions/utils.php#L87) but does not check if it is a list of terms first.

**Comment by jeffpaul** [comment]
Since this has not been prioritized by the Sophi team, I'm moving this out to the 1.1.0 milestone.

**Comment by jeffpaul** [comment]
@barryceelen noting that this was for a post type that does not have a taxonomy associated with it, is that a current impact for posts/pages on your client site or just a note from testing a random CPT?

**Comment by barryceelen** [comment]
@jeffpaul our site uses a post type without a taxonomy, which is indexed by sophi. As a result, the error logs keep filling up with this error. The fix would be to scan the plugin looking at where it wants to use [get_the_terms()](https://github.com/globeandmail/sophi-for-wordpress/blob/develop/includes/functions/utils.php#L87) and do the due diligence of checking its return value before using it.

**Comment by jeffpaul** [comment]
Relates to https://voltron.atlassian.net/servicedesk/customer/portal/41/SIT-2935
