### ISSUE TITLE
Automation block wants to retrieve result set while updating its settings

### ISSUE THREAD

**Issue by barryceelen** [globeandmail/sophi-for-wordpress#216]
### Is your enhancement related to a problem? Please describe.

The automation block starts fetching results while typing the page and widget name. While not strictly a problem, consider adding a delay or otherwise only fetch results after the settings for the block are completed

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jeffpaul** [comment]
@faisal-alvi this might be something worth considering as you update the Sophi block to the nested version as part of #328.

**Comment by dkotter** [comment]
My suggestion here would be to utilize debouncing here to ensure we don't send off a request until a user is done typing.

WordPress provides a few handy HOCs that we can utilize here: [`debounce`](https://developer.wordpress.org/block-editor/reference-guides/packages/packages-compose/#debounce) or [`useDebounce`](https://developer.wordpress.org/block-editor/reference-guides/packages/packages-compose/#usedebounce).

Might take some refactoring to make this work with our current edit component but would definitely be a nicer outcome than what we're doing now.

For more references, the ServerSideRender component was refactored [here](https://github.com/WordPress/gutenberg/pull/28297) to utilize debouncing, so might be useful as a guide. Also WordPress uses `lodash` behind the scenes for the debounce functionality, so can reference this [guide](https://lodash.com/docs/4.17.15#debounce) for more information on that.
