### ISSUE TITLE
Fix incorrect variable names

### ISSUE THREAD

**Issue by Sidsector9** [globeandmail/sophi-for-wordpress#247]
### Is your enhancement related to a problem? Please describe.

In few places, the return value of `wp_remote_get` is assigned to a variable called `$request` instead of `$response`.

For example:

https://github.com/globeandmail/sophi-for-wordpress/blob/23a26be24eec064a68e5fa5b526726372d41a3fd/includes/classes/SiteAutomation/Request.php#L213

This can be confusing and can be improved.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cadic** [comment]
Another occurence:

https://github.com/globeandmail/sophi-for-wordpress/blob/faaea9152555d02fc4dff96c3ae6c57607a9c349/includes/classes/SiteAutomation/Auth.php#L73-L79

**Comment by cadic** [comment]
In both `Request::request()` and `Auth::request_access_token()` functions, the actual `$response` is being assigned later after conditional checks.

In this case, `$result` looks like a better variable name for the result of `wp_remote_get`

**Comment by jeffpaul** [comment]
Leaving a note here that when we resolve this in a PR that we'll want to be precise in the changelog entry about this change in case someone's already relying on the "wrong" names?
