### ISSUE TITLE
Warning on displaying the page with Sophi Block

### ISSUE THREAD

**Issue by cadic** [globeandmail/sophi-for-wordpress#270]
### Describe the bug

Happens on the very first page view after creation. Doesn't reproduce after page refresh

Warning: Trying to access array offset on value of type bool in /wp-content/plugins/sophi/includes/classes/SiteAutomation/Request.php on line 187

### Steps to Reproduce

1. Make a new install
2. Create a page with Sophi Block
3. View the page

### Screenshots, screen recording, code snippet

<img width="1264" alt="image" src="https://user-images.githubusercontent.com/288381/168013196-b3f16b5d-092d-4920-b569-2cd79bbe06de.png">

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jeffpaul** [comment]
Perhaps our initial `if` condition isn't capturing this scenario?
https://github.com/globeandmail/sophi-for-wordpress/blob/ab0574d0b2ceb0751f18187e90849d0f55ba2d04/includes/classes/SiteAutomation/Request.php#L186-L190
