### ISSUE TITLE
SyncEmitter produce output in debug mode

### ISSUE THREAD

**Issue by cadic** [globeandmail/sophi-for-wordpress#271]
### Describe the bug

Initially reported in https://github.com/10up/sophi-debug-bar/issues/13

Happens when

`sophi_tracker_emitter_debug` is true (f.e. using Debug Bar for Sophi plugin)
AND
The directory `vendor/snowplow/snowplow-tracker/debug` isn't writable

When the SyncEmitter being created with `$debug = true` attribute, it will also try to write logs in the hardcoded path:

https://github.com/snowplow/snowplow-php-tracker/blob/32a08e9a7c25d1c51621751e1cdfcffcdef6cfe5/src/Emitter.php#L377-L379

If the path is not writable, Emitter will print the debug information

https://github.com/snowplow/snowplow-php-tracker/blob/32a08e9a7c25d1c51621751e1cdfcffcdef6cfe5/src/Emitter.php#L60-L65

### Steps to Reproduce

Refer to the initial report: https://github.com/10up/sophi-debug-bar/issues/13

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cadic** [comment]
I see 2 possible solutions:

### 1. Extend SyncEmitter

```php
class SophiEmitter extends Snowplow\Tracker\Emitters\SyncEmitter {
    const DEBUG_LOG_FILES = false;
}
```

then replace SyncEmitter with SophiEmitter here:

https://github.com/globeandmail/sophi-for-wordpress/blob/93e5495bae6b0222ef0034c3af18e761f39680ca/includes/functions/content-sync.php#L214

### 2. Suppress all output in debug mode

Add a conditional ob_start / ob_end_clean wrapper for $tracker->trackUnstructEvent in:

https://github.com/globeandmail/sophi-for-wordpress/blob/93e5495bae6b0222ef0034c3af18e761f39680ca/includes/functions/content-sync.php#L148

**Comment by cadic** [comment]
Solution 1 will not work: the Snowplow\Tracker\Emitter [is using self::DEBUG_LOG_FILES](https://github.com/snowplow/snowplow-php-tracker/blob/32a08e9a7c25d1c51621751e1cdfcffcdef6cfe5/src/Emitter.php#L60-L65) to read the const, in this case it always be `true`, as it was initially set in the [parent class declaration](https://github.com/snowplow/snowplow-php-tracker/blob/32a08e9a7c25d1c51621751e1cdfcffcdef6cfe5/src/Constants.php#L50)

```php
if (self::DEBUG_LOG_FILES) {
	if ($this->initDebug($type) !== true) {
		$this->write_perms = false;
		print_r("Unable to create debug log files: invalid write permissions.");
	}
}
```

**Comment by cadic** [comment]
Looks like it's still possible to extend `SyncEmitter` and overload it's [`makeDir` and other file methods](https://github.com/snowplow/snowplow-php-tracker/blob/32a08e9a7c25d1c51621751e1cdfcffcdef6cfe5/src/Emitter.php#L204-L213) to fake write failure since we don't want any uncontrolled logging from the 3rd party.

**Comment by cadic** [comment]
So, as the result, we need to combine both solutions:

1. Extending SyncEmitter with overloaded file methods will suppress writing log files if the `vendor/snowplow/snowplow-tracker/debug` is writable
2. Adding ob_start / ob_end_clean wrapper for `$tracker->trackUnstructEvent()` will suppress stdout if the directory is not writable.

**Comment by jeffpaul** [comment]
@cadic great triage on this, similarly confirming this also impacts publishing (not just updating as https://github.com/10up/sophi-debug-bar/issues/13 notes)
