### ISSUE TITLE
Same content for blocks with different settings

### ISSUE THREAD

**Issue by cadic** [globeandmail/sophi-for-wordpress#278]
### Describe the bug

If two or more blocks with different settings are added to a page, both are displayed with the same content.

While the website performs 2 requests to Sophi API and receives different data.

### Steps to Reproduce

1. Create new page
2. Add 2 Sophi blocks with the same "Page name" and different "Widget name"
3. Check with Debug Bar for Sophi: 2 API calls are performed
4. Both blocks have same content

### Screenshots, screen recording, code snippet

<img width="1276" alt="Screenshot 2022-05-17 at 13 54 10" src="https://user-images.githubusercontent.com/288381/168795886-5ea79bd3-99e5-4033-9a9c-1ad431be75d1.png">
<img width="1003" alt="Screenshot 2022-05-17 at 13 55 16" src="https://user-images.githubusercontent.com/288381/168795917-b6c8bb78-c60b-4ea6-9ac8-3f315cb87ddf.png">

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Sidsector9** [comment]
Closing as resolved in PR #281
