### ISSUE TITLE
Reverting the change done for sectionNames in https://github.com/globeandmail/sophi-for-wordpress/pull/308

### ISSUE THREAD

**Issue by vjayaseelan90** [globeandmail/sophi-for-wordpress#309]
### Is your enhancement related to a problem? Please describe.

Background: Sophi content_update schema introduced allSection to capture which section an article is published under and also which sections the article is eligible to be published under. When onboarding Rogers allSections was not available and since Sophi has allSections available now allSections should be mapped from get_post_categories_paths which is happening correctly in https://github.com/globeandmail/sophi-for-wordpress/pull/308. No changes needed here.

The sectionNames field mapping was also updated in https://github.com/globeandmail/sophi-for-wordpress/pull/308 and should be reverted back to the mapping which was followed in the previous version of the plugin. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jeffpaul** [comment]
@vjayaseelan90 to confirm, you had previously asked to sync the data in `allSections` and `sectionNames` and now you want that reverted?

cc: @YMufleh @smatta-tgam looking to one of you to double-confirm on this so I don't end up doing additional unnecessary work here.

**Comment by vjayaseelan90** [comment]
@jeffpaul : Yes, that is correct. For the time being we want to keep the `sectionNames`   mapping as it was in the previous version of the plugin and `allSections` can be mapped from get_post_categories_paths. 

Here is the future plan for `sectionNames` mapping

1. For now keep the `sectionNames` mapping as it was in the previous version of the plugin and the `allSections` should be mapped from get_post_categories_paths
2.  Once step one is completed, Sophi will ask Rogers to update the plugin so Sophi starts receiving `allSections `information from Rogers
3. Sophi will then change the configs to look at allSections instead of sectionNames 
4. Then there should be another update to the sectionNames mapping to only reflect primary section information. 

The `sectionNames` mapping cannot directly be updated to reflect primary section as this will be a breaking change for Sophi. So we want to keep the existing sectionNames mapping as is and first start receiving `allSections` information and then update the mapping for `sectionNames`

cc: @smatta-tgam
