### ISSUE TITLE
allow clients to add to the sectionNames array

### ISSUE THREAD

**Issue by YMufleh** [globeandmail/sophi-for-wordpress#315]
### Is your enhancement related to a problem? Please describe.

Would like clients using the plugin to have the ability to add to the sectionNames array from their taxonomies. 

### Designs

Create new filter called 

apply_filters( 'sophi_add_to_sections', $newSectionData )
This takes an array or string as input from the client and appends the items to the 

allSections array. before the plugin sends the published data to sophi endpoint

In the case of global news the field is the regional taaxonomy
$newSectionData = ['bc/okanagan','bc/vancouver'] <-- regional taxonomies array

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by iamdharmesh** [comment]
Hi @YMufleh, 

Thanks for opening the issue.

We have an existing filter [`sophi_post_data`](https://globeandmail.github.io/sophi-for-wordpress/sophi_post_data.html) which can be used to modify/extend post data before sending it to the Sophi endpoint. for example, we can append array items to  `allSections` before sending it to Sophi like below.

```php
add_filter( 'sophi_post_data', 'sophi_extend_post_data' );
function sophi_extend_post_data( $post_data ) {
	$post_data['allSections'] = array_merge( $post_data['allSections'], array( 'bc/okanagan', 'bc/vancouver' ) );
	// ... modify other post data like "sectionNames" if required.
	return $post_data;
}

```

Please let me know if the given snippet does not work for you or if I missed anything here.


Thanks
cc: @jeffpaul

**Comment by YMufleh** [comment]
Thank you @iamdharmesh , 
I don't see that in the documentation . specifically ```sophi_extend_post_data```

**Comment by YMufleh** [comment]
Ok Thank you @iamdharmesh  
I assume we can use a similar method to add a net new field. videoID which I was going to create an issue for

**Comment by YMufleh** [comment]
```
add_filter( 'sophi_post_data', 'sophi_extend_post_data' );
function sophi_extend_post_data( $post_data ) {
	$post_data['videoIds'] =  array( 'videoId1', 'videoId2' ) ;
	// ... modify other post data like "sectionNames" if required.
	return $post_data;
}
```

**Comment by jeffpaul** [comment]
Closing this via the work available in https://github.com/globeandmail/sophi-for-wordpress/blob/develop/hookdocs/modify-post-data.md#modify-existing-data
