### ISSUE TITLE
update sophi.data to reflect custom post type

### ISSUE THREAD

**Issue by YMufleh** [globeandmail/sophi-for-wordpress#326]
### Is your enhancement related to a problem? Please describe.

When users publish a custom post type that is a video. 
The FE should have that data reflected in the ```sophi.data``` object. 
that is,

```sophi.data.page.type = 'video'``` (currenly it is set at 'section'`) 
& 
``` sophi.data.content.type = 'video'``` 

sophi.data.content should reflect that content as well. 

The tracker will pick up on those values and report them. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by iamdharmesh** [comment]
Hi @YMufleh, 

Thanks for opening the issue, I just looked at the [code](https://github.com/globeandmail/sophi-for-wordpress/blob/develop/includes/functions/tracking.php#L88) and it seems the code is already there to get content type of post. Also, looking at the given [example video](https://globalnews-ca-develop.go-vip.net/video/7934708/manitoba-liquor-and-lotteries-ceo-explains-2-upcoming-covid-19-vaccine-lotteries/), it seems these aren't considered single post type pages. Not sure how these are being built on the theme side but it's registering this as the `homepage`.

In this case, they'll need to utilize the filter (`sophi_tracking_data`) to modify the data appropriately, I have created [PR](https://github.com/globeandmail/sophi-for-wordpress/pull/327) to add a tutorial doc on how to modify tracking data before sending it to Sophi.

![image](https://user-images.githubusercontent.com/10613171/189338964-468f0002-7b68-46a0-acfd-c23004aea90a.png)

Thanks.
cc: @jeffpaul @dkotter
