### ISSUE TITLE
Add tracker request endpoint config option

### ISSUE THREAD

**Issue by YMufleh** [globeandmail/sophi-for-wordpress#341]
### Is your enhancement related to a problem? Please describe.

Current state of the plugin, 

The Sophi tracker is requested (out of the box) from `https://cdn.sophi.io/latest/sophi.min.js`  

We want to give users the option to set this string from the plugin settings page so that they can request a dedicated tracker built for them specifically

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jeffpaul** [comment]
@YMufleh is there any sort of format or validation we should have on that field?  Is there a term for what you will refer to this as for us to label the field (e.g, "Sophi tracker")?

**Comment by YMufleh** [comment]
Thank you @jeffpaul  I can't think of a format, just that it should be a url. 

Can we call it `Sophi Tracker Address`

**Comment by jeffpaul** [comment]
@faisal-alvi tagging you to pick this up as soon as you wrap on the Overrides work as this change is needed in the bundled 1.3.0 release as well.  Essentially, in the plugin settings page's "Collector settings" please add a third item there called "Tracker Address" that defaults to "https://cdn.sophi.io/latest/sophi.min.js" as the value but can be changed by a user as desired.  Note that this appears to come in currently hardcoded via https://github.com/globeandmail/sophi-for-wordpress/blob/fd2a5d9f06819697ba5de88db4bb2b1c020a05b9/assets/js/frontend/sophi-tag.js#L28, so we'll want to update there and anywhere else this value will be referenced to use what is set in the new settings page variable.
