### ISSUE TITLE
The whole plugin stops working even if any one of the setting is left empty

### ISSUE THREAD

**Issue by vjayaseelan90** [globeandmail/sophi-for-wordpress#356]
### Describe the bug

The plugin has the following setting 

- Environment 
- Collector settings 
- Site Automation settings
- Override settings
- Advanced settings

If anyone of the setting is not populated, the whole plugin fails. 

In the plugin, each section should work on its own regardless of whether other section settings or populated or not

### Steps to Reproduce

1. Go to the sophi.io settings
2. Leave either Site Automation or Overrides setting empty
3. Even if the Collector setting are correct, the plugin will not be calling the Sophi tracker. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jeffpaul** [comment]
Let's ensure we're validating the settings/connection for each item in the plugin settings page (i.e. Collector, Site Automation, and Override) and allowing each to operate within the plugin even if others are not properly configured.  We should still throw an admin error notice if any of those settings sections are misconfigured/invalid after saving the settings page.
