### ISSUE TITLE
Add data attributes to site automation widgets

### ISSUE THREAD

**Issue by dkotter** [globeandmail/sophi-for-wordpress#63]
In order to better capture widget groupings, we need to add a new data attribute to the main container that is used for the site automation widgets.

This attribute takes the form `data-sophi-feature="Widget Name"`

As an example:
```
<div class="wp-block-trending" data-sophi-feature="trending"> 
    <h3>Trending</h3>
    <ul>...</ul>
</div>
```

We currently have a widget name field on the Site Automation block, so I propose that name is what is used for this data attribute. From the examples we've been given, it looks like this name should be lowercase and spaces should be replaced with dashes, so might need to pass the widget name through sanitization to achieve this.

For direct integrations with `WP_Query`, this data attribute will need to be added on a site-by-site basis. We probably need to update documentation to mention this.

**Comment by dinhtungdu** [comment]
@dkotter For Site Automation Block, we just output the list of curated posts wrapped inside `ul` tags, so I add data attributes to that `ul` tag in #64 instead of what you described above.

About the naming, why don't we use `widget` to unify the term?

> For direct integrations with WP_Query, this data attribute will need to be added on a site-by-site basis. We probably need to update documentation to mention this.

We have a section on WP_Query integration in the `README.md`: https://github.com/globeandmail/sophi-for-wordpress#query-integration.

**Comment by dkotter** [comment]
> For Site Automation Block, we just output the list of curated posts wrapped inside `ul` tags, so I add data attributes to that `ul` tag in #64 instead of what you described above

I'm thinking maybe we should add an extra `<div>` around the content that gets output where this attribute will live. And this `<div>` should live outside of the filtered HTML. At the moment, we recommend people use the `sophi_site_automation_block_output` filter to change that markup which means they would lose any data attribute we add (and they would have to manually add that). If we add an extra `<div>` with this attribute and move that `<div>` outside of our filter, that would solve that problem.

> About the naming, why don't we use `widget` to unify the term?

I'm fine with that but it's more of a question for the Sophi team I think, as the example is what they asked for

> We have a section on WP_Query integration in the `README.md`

Yep, saw that. I'm just thinking we might want to enhance that section with details on adding this data attribute themselves if they use that integration type

**Comment by dinhtungdu** [comment]
@dkotter Thanks so much for the clarification! #64 is ready to review again.
